### ISSUE TITLE
A New Empirical Evaluation of ChatGPT for Recommender System

### ISSUE THREAD

**Issue by KID-22** [THU-KEG/EvaluationPapers4ChatGPT#10]
Hello! Our new work titled ‘Uncovering ChatGPT’s Capabilities in Recommender Systems’ has been released and can be found at https://arxiv.org/pdf/2305.02182.pdf. We have also open-sourced our code and detailed results at https://github.com/rainym00d/LLM4RS. We kindly request that you add it to this repository. Thank you!

**Comment by KID-22** [comment]
We evaluate LLMs (ChatGPT and GPT3.5s) for recomendation from point-wise, pair-wise and list-wise persepectives on four widely-used datasets from movie, book, music, news domains. And we test on 500 samples for each dataset.

**Comment by ShangQingTu** [comment]
Nice work! 🤗

**Comment by KID-22** [comment]
Thank you very much!
