### ISSUE TITLE
No "Question Answering" Category?

### ISSUE THREAD

**Issue by jeffhj** [THU-KEG/EvaluationPapers4ChatGPT#13]
Thank you for maintaining this repository.

We have a study titled, "Why Does ChatGPT Fall Short in Providing Truthful Answers?" (https://arxiv.org/abs/2304.10513), which I believe is relevant to this repository. However, I noticed that there is no specific category for Q&A to place this work under :)

**Comment by ShangQingTu** [comment]
Hi, thanks for you suggestion.
We mainly put Q&A works under the reasoning category.

**Comment by ShangQingTu** [comment]
Hi, I have added your paper~
