### ISSUE TITLE
申请往ReadMe添加一个医学方向的evaluation report！

### ISSUE THREAD

**Issue by shan23chen** [THU-KEG/EvaluationPapers4ChatGPT#5]
https://github.com/AIM-Harvard/ChatGPT_NCCN
MedRxiv等待审核
google drive内有详细model output， annotation，还有scoring guidelines！
谢谢！

**Comment by ShangQingTu** [comment]
感谢您的贡献，我先把github加上，等有MedRxiv链接之后再更新一下。
Thank you for your contribution. I'll add github link first and update it later when there is a link on MedRxiv.

**Comment by ShangQingTu** [comment]
OK
